## examples/system_monitor/system_monitor.nim — M27 demo: Sparkline +
## DataTable showing fake CPU / memory stats.
##
## Demonstrates:
##   * `Sparkline` (M21) for time-series visualisation
##   * `DataTable` (M17) for tabular per-process stats
##
## All data is generated by a deterministic LCG so the snapshot is
## stable across runs. No real `/proc` reads or syscalls — that would
## introduce platform variance and break the snapshot contract.

import isonim_tui

# ----------------------------------------------------------------------------
# Deterministic data generator
# ----------------------------------------------------------------------------

proc lcg(state: var uint64): uint64 =
  state = state * 6364136223846793005'u64 + 1442695040888963407'u64
  state

proc cpuSeries*(): seq[float64] =
  ## 60 ticks of "CPU %" data — values in [10, 90]. Deterministic.
  result = newSeq[float64](60)
  var s: uint64 = 1
  for i in 0 ..< 60:
    let r = lcg(s)
    result[i] = 10.0 + (float64((r shr 33) and 0xFFFF) / 65535.0) * 80.0

proc memSeries*(): seq[float64] =
  ## 60 ticks of "MEM %" data — values in [40, 70].
  result = newSeq[float64](60)
  var s: uint64 = 73
  for i in 0 ..< 60:
    let r = lcg(s)
    result[i] = 40.0 + (float64((r shr 33) and 0xFFFF) / 65535.0) * 30.0

# Per-process fake table.
const Processes* = [
  ("pid",   "name",        "cpu",  "mem"),
  ("100",   "init",        " 0.1", "  4"),
  ("412",   "systemd",     " 0.5", " 12"),
  ("903",   "rsyslogd",    " 0.2", "  8"),
  ("1024",  "nginx",       " 1.4", " 18"),
  ("1582",  "postgres",    " 3.7", "120"),
  ("1734",  "redis",       " 0.8", " 22"),
  ("2010",  "nim",         "12.4", "210"),
  ("2042",  "isonim_tui",  " 4.1", " 65"),
  ("2099",  "fish",        " 0.0", "  6")]

# ----------------------------------------------------------------------------
# Composition
# ----------------------------------------------------------------------------

proc buildSystemMonitorApp*(h: TerminalTestHarness): TerminalNode =
  let r = h.renderer
  let root = r.createElement("div")
  r.setAttribute(root, "class", "system-monitor")

  # Header.
  let header = newHeader(r, title = "System Monitor",
                         subtitle = "deterministic fixture",
                         width = h.cols)
  r.appendChild(root, header.node)

  # CPU sparkline.
  let cpuLabel = newStatic(r, " CPU %", width = h.cols, height = 1)
  r.appendChild(root, cpuLabel.node)
  let sp1 = newSparkline(r, data = cpuSeries(),
                         width = h.cols, height = 2, summary = sumMax)
  r.appendChild(root, sp1.node)

  # Memory sparkline.
  let memLabel = newStatic(r, " MEM %", width = h.cols, height = 1)
  r.appendChild(root, memLabel.node)
  let sp2 = newSparkline(r, data = memSeries(),
                         width = h.cols, height = 2, summary = sumMean)
  r.appendChild(root, sp2.node)

  # Per-process table.
  let columns = @[
    ColumnDef(key: "pid",  label: "pid",  width: 6),
    ColumnDef(key: "name", label: "name", width: 16),
    ColumnDef(key: "cpu",  label: "cpu",  width: 6),
    ColumnDef(key: "mem",  label: "mem",  width: 6)]

  var rows: seq[RowData] = @[]
  for i in 1 ..< Processes.len:    # skip header tuple
    let p = Processes[i]
    rows.add RowData(cells: @[$p[0], $p[1], $p[2], $p[3]])

  let dt = newDataTable(r, columns = columns, rows = rows,
                        viewportHeight = max(rows.len + 1, 6),
                        border = bsSolid)
  r.appendChild(root, dt.node)

  root

proc mountSystemMonitor*(h: TerminalTestHarness) =
  h.mount(proc(r: TerminalRenderer): TerminalNode =
    discard r
    buildSystemMonitorApp(h))

when isMainModule:
  let h = newTerminalTestHarness(60, 22)
  mountSystemMonitor(h)
  echo "System monitor mounted (", h.cols, "x", h.rows, ")."
  echo "CPU samples: ", cpuSeries().len, " mem: ", memSeries().len
  h.dispose()
