## Unicode table generator for isonim-tui.
##
## Reads the vendored Unicode reference files under
## `tests/fixtures/unicode/` and emits two Nim source files that the
## production text layer imports:
##
##   * `src/isonim_tui/text/east_asian_width_table.nim`
##   * `src/isonim_tui/text/grapheme_break_table.nim`
##   * `src/isonim_tui/text/emoji_table.nim`
##
## We emit packed `seq` of `(rangeStart, rangeEnd, value)` tuples plus a
## binary-search lookup. Tables are large enough that compile-time
## construction would slow builds; running the generator once per
## Unicode release and committing the output keeps every build hermetic
## and fast.
##
## Usage:
##   nim r tools/generate_unicode_tables.nim
##
## All paths resolved relative to the repo root (where this tool's
## generated files are checked in).

import std/[strutils, os, algorithm]

type
  Range = tuple[lo, hi, value: int]

proc parseHex(s: string): int =
  ## Parse a hex string like "1F1E6". Returns -1 on failure.
  result = 0
  let s2 = s.strip()
  if s2.len == 0: return -1
  for ch in s2:
    case ch
    of '0' .. '9': result = result * 16 + (ch.ord - '0'.ord)
    of 'a' .. 'f': result = result * 16 + (ch.ord - 'a'.ord + 10)
    of 'A' .. 'F': result = result * 16 + (ch.ord - 'A'.ord + 10)
    else: return -1

# ----------------------------------------------------------------------------
# Generic UCD parser
# ----------------------------------------------------------------------------

proc parseUcdLines(path: string; valueMap: proc(s: string): int): seq[Range] =
  ## Parse a Unicode property file: every non-empty, non-comment line has
  ## "RANGE ; VALUE # comment". valueMap maps the property string to an
  ## integer code; returning -1 means "skip".
  result = @[]
  for line in lines(path):
    let hashIdx = line.find('#')
    let body =
      if hashIdx >= 0: line[0 ..< hashIdx]
      else: line
    let trimmed = body.strip()
    if trimmed.len == 0: continue
    let parts = trimmed.split(';')
    if parts.len < 2: continue
    let rangeStr = parts[0].strip()
    let propStr = parts[1].strip()
    let v = valueMap(propStr)
    if v < 0: continue
    var lo, hi: int
    let dotIdx = rangeStr.find("..")
    if dotIdx >= 0:
      lo = parseHex(rangeStr[0 ..< dotIdx])
      hi = parseHex(rangeStr[dotIdx + 2 .. ^1])
    else:
      lo = parseHex(rangeStr)
      hi = lo
    if lo < 0 or hi < 0: continue
    result.add((lo, hi, v))
  result.sort(proc(a, b: Range): int = cmp(a.lo, b.lo))

# ----------------------------------------------------------------------------
# East Asian Width
# ----------------------------------------------------------------------------

proc eawValue(s: string): int =
  case s
  of "F": 0       # Fullwidth (wide)
  of "W": 0       # Wide
  of "A": 1       # Ambiguous
  of "H": 2       # Halfwidth
  of "Na": 3      # Narrow
  of "N": 3       # Neutral
  else: -1

proc generateEastAsianWidth(srcPath, outPath: string) =
  let ranges = parseUcdLines(srcPath, eawValue)
  var s = """## Generated by tools/generate_unicode_tables.nim — DO NOT EDIT BY HAND.
##
## East Asian Width property table (Unicode 16.0.0).
##
## Values:
##   eawWide      = 0  (W or F, always width 2)
##   eawAmbiguous = 1  (width depends on context — default narrow)
##   eawHalf      = 2  (width 1)
##   eawNarrow    = 3  (width 1)
##
## All other code points default to Neutral (width 1).

type
  EawClass* = enum
    eawWide
    eawAmbiguous
    eawHalf
    eawNarrow

const eawTable*: array[0 .. ?n, tuple[lo, hi: int32, cls: int8]] = [
""".replace("?n", $(ranges.len - 1))
  for i, r in ranges:
    let comma = if i + 1 < ranges.len: "," else: ""
    s.add("  (" & $r.lo & "i32, " & $r.hi & "i32, " & $r.value & "i8)" & comma & "\n")
  s.add("""]

proc eawClass*(cp: int32): EawClass =
  ## Look up the East Asian Width class of a code point. Defaults to
  ## `eawNarrow` for anything not in the table (matches the spec's
  ## "Neutral" default behaviour for our purposes).
  ##
  ## Binary-search the sorted (lo, hi, cls) ranges.
  var lo = 0
  var hi = eawTable.len - 1
  while lo <= hi:
    let mid = (lo + hi) shr 1
    if cp < eawTable[mid].lo:
      hi = mid - 1
    elif cp > eawTable[mid].hi:
      lo = mid + 1
    else:
      return EawClass(eawTable[mid].cls)
  return eawNarrow
""")
  writeFile(outPath, s)
  echo "wrote ", outPath, " with ", ranges.len, " ranges"

# ----------------------------------------------------------------------------
# Grapheme Break Property
# ----------------------------------------------------------------------------

proc gbpValue(s: string): int =
  case s
  of "CR": 0
  of "LF": 1
  of "Control": 2
  of "Extend": 3
  of "ZWJ": 4
  of "Regional_Indicator": 5
  of "Prepend": 6
  of "SpacingMark": 7
  of "L": 8
  of "V": 9
  of "T": 10
  of "LV": 11
  of "LVT": 12
  else: -1

proc generateGraphemeBreak(srcPath, outPath: string) =
  let ranges = parseUcdLines(srcPath, gbpValue)
  var s = """## Generated by tools/generate_unicode_tables.nim — DO NOT EDIT BY HAND.
##
## Grapheme_Cluster_Break property table (Unicode 16.0.0).
##
## Maps code points to enum values matching UAX #29.

type
  GraphemeBreakKind* = enum
    gbOther
    gbCR
    gbLF
    gbControl
    gbExtend
    gbZWJ
    gbRegionalIndicator
    gbPrepend
    gbSpacingMark
    gbL
    gbV
    gbT
    gbLV
    gbLVT

const gbpTable*: array[0 .. ?n, tuple[lo, hi: int32, cls: int8]] = [
""".replace("?n", $(ranges.len - 1))
  # Map our integer encoding (0..12) to the GraphemeBreakKind ord by
  # remembering that gbOther = 0; everything else shifts by +1 because
  # we added a leading "gbOther" alias.
  for i, r in ranges:
    let kind = r.value + 1
    let comma = if i + 1 < ranges.len: "," else: ""
    s.add("  (" & $r.lo & "i32, " & $r.hi & "i32, " & $kind & "i8)" & comma & "\n")
  s.add("""]

proc graphemeBreakKind*(cp: int32): GraphemeBreakKind =
  var lo = 0
  var hi = gbpTable.len - 1
  while lo <= hi:
    let mid = (lo + hi) shr 1
    if cp < gbpTable[mid].lo:
      hi = mid - 1
    elif cp > gbpTable[mid].hi:
      lo = mid + 1
    else:
      return GraphemeBreakKind(gbpTable[mid].cls)
  return gbOther
""")
  writeFile(outPath, s)
  echo "wrote ", outPath, " with ", ranges.len, " ranges"

# ----------------------------------------------------------------------------
# Emoji table — Extended_Pictographic only (the value GB11 cares about)
# ----------------------------------------------------------------------------

proc emojiValue(s: string): int =
  if s == "Extended_Pictographic": 0
  else: -1

# ----------------------------------------------------------------------------
# Indic Conjunct Break (InCB) — 3-field UCD lines.
# ----------------------------------------------------------------------------

proc parseInCBLines(path: string): seq[Range] =
  ## Parse DerivedCoreProperties lines whose property is `InCB`. Three
  ## fields: range ; "InCB" ; "Linker"|"Consonant"|"Extend".
  result = @[]
  for line in lines(path):
    let hashIdx = line.find('#')
    let body =
      if hashIdx >= 0: line[0 ..< hashIdx]
      else: line
    let trimmed = body.strip()
    if trimmed.len == 0: continue
    let parts = trimmed.split(';')
    if parts.len < 3: continue
    if parts[1].strip() != "InCB": continue
    let valStr = parts[2].strip()
    let v =
      case valStr
      of "Linker": 1
      of "Consonant": 2
      of "Extend": 3
      else: -1
    if v < 0: continue
    let rangeStr = parts[0].strip()
    var lo, hi: int
    let dotIdx = rangeStr.find("..")
    if dotIdx >= 0:
      lo = parseHex(rangeStr[0 ..< dotIdx])
      hi = parseHex(rangeStr[dotIdx + 2 .. ^1])
    else:
      lo = parseHex(rangeStr)
      hi = lo
    if lo < 0 or hi < 0: continue
    result.add((lo, hi, v))
  result.sort(proc(a, b: Range): int = cmp(a.lo, b.lo))

proc generateInCB(srcPath, outPath: string) =
  let ranges = parseInCBLines(srcPath)
  var s = """## Generated by tools/generate_unicode_tables.nim — DO NOT EDIT BY HAND.
##
## Indic Conjunct Break (InCB) property — DerivedCoreProperties.
## Used by GB9c (Unicode 15.1+).

type
  InCBKind* = enum
    incbNone
    incbLinker
    incbConsonant
    incbExtend

const incbTable*: array[0 .. ?n, tuple[lo, hi: int32, cls: int8]] = [
""".replace("?n", $(ranges.len - 1))
  for i, r in ranges:
    let comma = if i + 1 < ranges.len: "," else: ""
    s.add("  (" & $r.lo & "i32, " & $r.hi & "i32, " & $r.value & "i8)" & comma & "\n")
  s.add("""]

proc inCBKind*(cp: int32): InCBKind =
  var lo = 0
  var hi = incbTable.len - 1
  while lo <= hi:
    let mid = (lo + hi) shr 1
    if cp < incbTable[mid].lo:
      hi = mid - 1
    elif cp > incbTable[mid].hi:
      lo = mid + 1
    else:
      return InCBKind(incbTable[mid].cls)
  return incbNone
""")
  writeFile(outPath, s)
  echo "wrote ", outPath, " with ", ranges.len, " ranges"

proc generateEmoji(srcPath, outPath: string) =
  let ranges = parseUcdLines(srcPath, emojiValue)
  var s = """## Generated by tools/generate_unicode_tables.nim — DO NOT EDIT BY HAND.
##
## Extended_Pictographic property (Unicode 16.0 / Emoji 16.0).
## Used by GB11 (ZWJ-emoji-sequence rule).

const extendedPictographicTable*: array[0 .. ?n, tuple[lo, hi: int32]] = [
""".replace("?n", $(ranges.len - 1))
  for i, r in ranges:
    let comma = if i + 1 < ranges.len: "," else: ""
    s.add("  (" & $r.lo & "i32, " & $r.hi & "i32)" & comma & "\n")
  s.add("""]

proc isExtendedPictographic*(cp: int32): bool =
  var lo = 0
  var hi = extendedPictographicTable.len - 1
  while lo <= hi:
    let mid = (lo + hi) shr 1
    if cp < extendedPictographicTable[mid].lo:
      hi = mid - 1
    elif cp > extendedPictographicTable[mid].hi:
      lo = mid + 1
    else:
      return true
  return false
""")
  writeFile(outPath, s)
  echo "wrote ", outPath, " with ", ranges.len, " ranges"

# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------

when isMainModule:
  let here = currentSourcePath().parentDir().parentDir()
  let fixtures = here / "tests" / "fixtures" / "unicode"
  let textDir = here / "src" / "isonim_tui" / "text"
  generateEastAsianWidth(fixtures / "EastAsianWidth.txt",
                         textDir / "east_asian_width_table.nim")
  generateGraphemeBreak(fixtures / "GraphemeBreakProperty.txt",
                        textDir / "grapheme_break_table.nim")
  generateEmoji(fixtures / "emoji-data.txt",
                textDir / "emoji_table.nim")
  generateInCB(fixtures / "DerivedCoreProperties.txt",
               textDir / "incb_table.nim")
  echo "all tables generated"
